language: python
python:
  - "3.6.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# Services for Travis
services: mongodb
# command to run tests
script:
  - python -m unittest discover tests
