- hosts: MongoDB
  sudo: true
  roles:
    - { role: undergreen.mongodb, tag: ansidev.mongodb }
  tasks:
    - name: Allow remote connections
      become: yes
      lineinfile:
        dest: /etc/mongod.conf
        regexp: "^\\s*bindIp.*"
        line: "  bindIp: 0.0.0.0"
        state: present
