---
  - hosts: all
    become: true
    pre_tasks:
      - name: Instala git
        apt:
          pkg: git
          state: present

      - name: Instalando herramientas necesarias
        sudo: yes
        apt:
          pkg: [wget,curl,python-minimal,python-setuptools,python-pip,python3-pip]
          state: present

    tasks:
      - name: Clonando repositorio github
        become: false
        git:
          repo: 'https://github.com/AlejandroCN7/Ejercicios_CC.git'
          clone: yes
          dest: ~/proyecto

      - name: Instalando dependencias del proyecto
        become: true
        pip:
          requirements: ~/proyecto/requirements.txt
          executable: pip3
